script:
- git remote add upstream $GIT_URL
- git fetch upstream
- cp -Rf .git/refs/remotes/upstream/* .git/refs/heads/
- rm -f .git/refs/heads/HEAD
- cat .git/packed-refs | grep ' refs/remotes/upstream/' | sed 's& refs/remotes/upstream/& refs/heads/&' >> .git/packed-refs
- git remote add fork https://github.com/$GITHUB_NAME/$GITHUB_REPO.git
- echo -e "machine github.com\nlogin $GITHUB_NAME\npassword $GITHUB_TOKEN" >> ~/.netrc
- git push fork --all
- git push fork --tags
branches:
  except:
    - /^deploy-.*$/
notifications:
  email: false
env:
  global:
  - GITHUB_NAME=$(echo $TRAVIS_REPO_SLUG | cut -d '/' -f 1)
  matrix:
  - GITHUB_REPO=peerguardian GIT_URL=https://git.code.sf.net/p/peerguardian/code
  - GITHUB_REPO=stg GIT_URL=http://git.stg.codes/stg.git
  - GITHUB_REPO=orbot GIT_URL=https://git.torproject.org/orbot.git
  - GITHUB_REPO=tor GIT_URL=https://git.torproject.org/tor.git
